/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dicoding.kotlin

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

//    val byteMinValue = Byte.MIN_VALUE
//    val byteMaxValue = Byte.MAX_VALUE
//    val shortMinValue = Short.MIN_VALUE
//    val shortMaxValue = Short.MAX_VALUE
//    val intMinValue = Int.MIN_VALUE
//    val intMaxValue = Int.MAX_VALUE
//    val longMinValue = Long.MIN_VALUE
//    val longMaxValue = Long.MAX_VALUE
//
//    val floatMinValue = Float.MIN_VALUE
//    val floatMaxValue = Float.MAX_VALUE
//    val doubleMinValue = Double.MIN_VALUE
//    val doubleMaxValue = Double.MAX_VALUE
//
//    println(byteMinValue)
//    println(byteMaxValue)
//    println(shortMinValue)
//    println(shortMaxValue)
//    println(intMinValue)
//    println(intMaxValue)
//    println(longMinValue)
//    println(longMaxValue)
//
//    println(floatMinValue)
//    println(floatMaxValue)
//    println(doubleMinValue)
//    println(doubleMaxValue)

    println(Gender.Pria)
    println(Gender.Pria.kind)

}
